### ISSUE TITLE
Bowtie and the World of JSON Schema

### ISSUE THREAD

**Issue by benjagm** [postman-open-technologies/gsoc-2023#15]
**Summary:** 
The world of JSON Schema is immense. JSON Schema tooling exists in countless languages across a variety of uses (data validation of course a noteworthy and prominent one). Implementing the JSON Schema specification(s) in a fully compliant way is not without challenge, meaning as a user of JSON Schema it is important to understand how a particular implementation may deviate such that one can make constructive tooling choices or help implementations improve. [Bowtie](https://github.com/bowtie-json-schema/bowtie/) is a recently created tool to aide in this task, helping to surface the conformance of various JSON Schema tools with the specification by running them against a set of [known correct test cases](https://github.com/json-schema-org/JSON-Schema-Test-Suite) and [regularly rendering the results to a web page](https://bowtie-json-schema.github.io/bowtie/). But it can do more!

**Expected Outcomes:**
Enhance (or replace) Bowtie's [simplistic current UI](https://bowtie-json-schema.github.io/bowtie/) so that it most easily answers "what do various implementations say about each test case" -- making it snappier and more featureful
Add support for further JSON Schema implementations by creating [Bowtie harnesses](https://bowtie-json-schema.readthedocs.io/en/latest/implementers/) in additional languages
Teach Bowtie to compare not only True/False validation results but also the [full JSON Schema standardized output formats](https://json-schema.org/specification.html#output-schemas-and-examples)

**Skills Required:**
HTML/CSS/Javascript familiarity
Some notion of what JSON Schema is -- or equivalently some experience using a similar data validation tool including writing SQL Schemas for databases
Basic experience with [any of a broad set of languages with JSON Schema implementations](https://json-schema.org/implementations.html#validators) or curiosity to learn enough about them to write a simple program
Some Python experience a strong plus

**Mentors:**
@Julian

**Project Repo:** tbd

**Expected Difficulty:**
Easy-Medium

**Expected Time Commitment:**
175 Hour

**Comment by Devaansh-Kumar** [comment]
Hey @benjagm @jansche I am  Devaansh Kumar a second year CSE student.

**Comment by Shrini3** [comment]
Hey I am excited to work on this project idea and I'm meeting all the prerequisite, any chance that I will be accepted as a contributor

**Comment by nomandhoni-cs** [comment]
Hi there! I'm Abdullah Al Noman, a passionate software developer with a focus on JavaScript and React.js. Here are some highlights of my experience and skills:
- 5+ completed projects and ongoing contributions to open-source projects
- Proficient in JavaScript and React.js
- Experience with various technologies and frameworks including Express.js, MongoDB, Git, Firebase, and Material UI
- Ability to tackle complex problems and break them down into manageable pieces
- Recent project: CRUD form application that showcased my expertise in MongoDB, Express.js, and React.js. I deployed my own API to enable form submissions, and the data is stored in the MongoDB database.

Passion for contributing to open-source projects and frequently engage in coding challenges on online judges like Codeforces, LeetCode, and HackerRank.

I'm a dedicated and driven software developer with a proven track record of success, and I'm eager to contribute my skills and experience to your team and help drive your projects to success.

**Comment by aku1310** [comment]
Hi,

Hope you're doing well. I have been looking at the project ideas for GSoC and this one really intrigues me. I am confident that my skills and experience make me capable of contributing to the project's success. As someone who has experience using JSON Schema and validating data, I understand the importance of implementing the JSON Schema specification in a fully compliant way.

I have a strong foundation in HTML, CSS, Javascript, SQL, etc. and I am eager to use my skills to contribute to this project idea. I am eager to learn more about JSON Schema implementation, and I am confident that my curiosity and willingness to learn will enable me to quickly adapt to new programming languages and write simple programs. Moreover, I have some experience with Python, which is a plus, and I am excited to apply it in the project.

I understand the expected difficulty level and time commitment of the project and assure you that I am fully committed to working on it. I am confident that my skills and enthusiasm will enable me to make a valuable contribution to this project.

Looking forward to more details about how one can contribute to this project.

**Comment by Julian** [comment]
Hey folks! Thanks for expressing interest.

A good first resource is definitely starting by familiarizing yourself with JSON Schema with the [learning resources](https://json-schema.org/learn/). [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/) in particular is a great resource to read.

You can then also read through a ton of examples of JSON Schema's behavior in the [official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) which is one of the key "sources of truth" Bowtie uses to assess implementations.

And then thirdly you can try and get Bowtie installed. There are some brief [install instructions in the docs](https://bowtie-json-schema.readthedocs.io/en/latest/#installation) which should work for macOS or Linux, and once you have it installed there are some [usage examples here](https://bowtie-json-schema.readthedocs.io/en/latest/cli/).

Feel free to follow up if you get stuck, and thanks again, I'm sure we'll be in touch with future GSoC contributors!

**Comment by benjagm** [comment]
Hi folks,
we're currently coordinating with mentors and will provide more details as well as answer questions beginning of next week (week of March 6). Please bear with us.
Best regards.
Ben

**Comment by semioz** [comment]
Greetings, everyone! My name is Semih, and I'm thrilled to be here to share my passion for software development. As a freshman software student, I have been working on various backend projects using technologies like JavaScript, TypeScript, Node.js, MongoDB, Redis and PostgreSQL. I also have familiarity in front-end technologies such as HTML, CSS, and React.js.

In addition to my technical skills, I have been actively contributing to the community as a Postman Student Expert for a year. My role involves helping students with APIs and Postman, and this experience has helped me develop my teamwork, communication, and problem-solving skills.

I'm excited to learn more about this Google Summer of Code project and contribute to the community by leveraging my skills and knowledge. My goal is to expand my expertise in software development and build relationships with fellow developers. I'm confident that this program will provide me with the perfect opportunity to achieve these goals.

**Comment by benjagm** [comment]
Hi everyone! Thanks a lot for your interest in this project Idea and JSON Schema! We'd like to run an Office Hours Session tomorrow at 09:00 PST, 18:00 CET, 22:30 IST, 14:00 BRT
This is the link to join: https://www.google.com/url?q=https://postman.zoom.us/j/87665681860?pwd%3DcjZkVnA1MHpWMFR0eXV6bS8raDN3UT09&sa=D&source=calendar&ust=1678707171237791&usg=AOvVaw1q9uGbTtKTLdK0y4ZbOIY0

In the meantime we invite you to join JSON Schema Slack server in the channel [#gsoc-2023](https://json-schema.slack.com/archives/C04MVQSRBRS) using this link: https://join.slack.com/t/json-schema/shared_invite/zt-1qnbilvie-_Tvbr6YQL29l2HZBNvCiDQ

@bbsemih @aku1310 @nomandhoni-cs @Shrini3 
@Julian

**Comment by dante381** [comment]
Hello,

I am a 3rd Computer Science student at KMIT Hyderabad, India. Over the past few years, I have worked on several Projects with Python and JavaScript and gained experience working with RESTful API. I have a basic understanding of Schemas for data validation in SQL.

I am thrilled about the opportunity to tackle the task of developing the various utilities outlined above as a mentee for GSoC this summer. I am eager to undertake the initial qualifying tasks and collaborate with the community towards completing this project.

Thank you.

**Comment by benjagm** [comment]
Hi everyone!! Thanks a lot for your interest in JSON Schema ideas. 

We invite you to join JSON Schema Slack server in the channel [#gsoc-2023](https://json-schema.slack.com/archives/C04MVQSRBRS) Join the server using this [link](https://join.slack.com/t/json-schema/shared_invite/zt-1qnbilvie-_Tvbr6YQL29l2HZBNvCiDQ)

In #gson-2023 channel you will find there: 1)resources, 2)recording of the last office hours session, 3)clear instructions to prepare your submission to this Project Idea and 4) the best place to get immediate support.

JSON Schema is all about Community and the Community is in Slack! See you there!

**Comment by VishrutAggarwal** [comment]
Hello everyone!

I came across the project while looking for GSoC projects and I'm very interested in contributing to it. I have experience with HTML/CSS/Javascript and basic knowledge of JSON Schema, including writing SQL Schemas for databases. I also have experience with Python, which I believe will be helpful for this project.

I'm excited about the expected outcomes, particularly enhancing Bowtie's UI to provide more comprehensive results and adding support for further JSON Schema implementations.

I'm looking forward to getting selected for this project.

Thank you for considering my interest.

**Comment by codesparsh** [comment]
Hello everyone! 

I'm Sparsh, currently working as a developer in Juspay technologies, delivering online payment solutions in India. I am excited about the work you are doing and I believe I can make a valuable contribution to the project.

I have 2 years of experience in React.Js, Haskell. I am familiar writing Json Schema's for SQL and mongodb databases. I am confident that I can quickly learn any new technologies required.

I believe that my skills and experience make me a strong candidate for this role. I am passionate about open source and I am committed to making a positive impact on the project.

Thank you for considering my application. I would be happy to provide additional information or answer any questions you may have.

**Comment by probablyArth** [comment]
Hey there!

I'm Arth, a fullstack developer. I have 2 years of experience with the MERN stack and have been in love with typescript since the last year. I have good experience on working with JSON for my side projects, and I've even published an npm library [Jason](https://www.npmjs.com/package/@probablyarth/jason) a typesafe orm for working with JSON files!

Really looking forward to working with you!
Thank you!

**Comment by MPrashanthR** [comment]
As a Full Stack Developer with experience in Python and SQL, you would be a great fit for the Bowtie project. i am familiarity with HTML/CSS/Javascript would be valuable in enhancing Bowtie's UI, and my experience with various programming languages would be helpful in creating Bowtie harnesses for additional JSON Schema implementations. my expertise in SQL schema design and data validation tools would also come in handy in understanding the JSON Schema specification and implementing its compliance testing. This project would provide me with the opportunity to work on a challenging and interesting project that would benefit the wider development community.

@Julian
@benjagm

**Comment by Raghucharan16** [comment]
Hello Everyone,

I am CS Undergraduate at Gayatri Vidya Parishad  (GVP) Visakhapatnam, India. I am always interested in Open Source Projects but never did any remarkable Contribution. As this is one of the prestigious Open Source Campaign where all of the developers Collaborate, share knowledge 
and built some useful product.
I have worked on several web related and Machine Learning projects. I have a decent knowledge in HTML, CSS, JavaScript. I'm recently more working on API's and Automation. I worked on Docker, Kubernetes and Google Cloud Platform. To me Learning in public makes the things clear and pretty easy. We built a sample calculator which calculates Fibonacci of nth given number and displays the result. I Collaborated with my peers and seniors and used React, Nodejs , and managed to spin up a local cluster and also deployed in Google Cloud Platform.  I have decent knowledge in SQL and able to write basic Queries.  I would like to learn more by doing and building.  We at our college participated,hosted several hackathons which include collaboration with peers, Coding Competitions.

Thank you 
 
I'll utilise this opportunity to full extent to excel and kickstart my journey in Open Source and my career. I have volunteered in many organisations like GDSC,GDG Vizag and did my part to grow the community.  I am eager to undertake the initial qualifying tasks and collaborate with the community towards completing this project.

**Comment by AgniveshChaubey** [comment]
Hello everyone,

I am Agnivesh, a pre-final year undergraduate student of electrical engineering with a strong interest in the tech domain. As a self-taught learner, I am always eager to explore new technologies and their applications. My passion lies in open-source development, creating a sense of community, and working on real-world solutions as an open-source enthusiast.

I have been actively learning and exploring open-source since November 2022, and have made some basic contributions to the Meshery and Layer5 projects. Through these experiences, I have gained a decent understanding of how open-source development works.

With a strong desire to learn and add values to the community, I am excited to take on new challenges and contribute my skills to this project.

Thank you

**Comment by Blackmamoth** [comment]
Hello everyone, please allow me to introduce myself. My name is Ashpak Veetar, and I'm a second-year computer science student. I'm currently working as a full-stack developer at a health tech company, and I'm passionate about learning new things and taking on challenges. Recently, I came across this open-source development project, and it caught my eye. I'm interested in contributing to this project as a way to learn something new, get challenged, and give back to the open-source community. Thank you for considering my interest in this project.

**Comment by benjagm** [comment]
Thanks a lot for your hard work with your messages and qualifying tasks! We are looking forward to receive your applications. Please ask us for feedback with your applications anytime, we'd love to help.

Please, join the JSON Schema **Slack server** using this [link](https://join.slack.com/t/json-schema/shared_invite/zt-1qnbilvie-_Tvbr6YQL29l2HZBNvCiDQ) and join channel [#gsoc-2023](https://json-schema.slack.com/archives/C04MVQSRBRS) to stay up to date with all the communications and announcements.

**Comment by bhavy0949** [comment]
Hello everyone,
My name is Bhavy, and I am excited to introduce myself as a prospective GSoC participant. I am a third year CSE student and I have a strong passion for web development, and I believe that it would be an incredible opportunity for me to contribute and gain real-world experience in the field. I am particularly interested in working on React and nodejs. I am also a quick learner and am eager to expand my knowledge and skills. I believe that GSoC would be an excellent opportunity for me to work with other like-minded individuals, gain valuable experience, and make a meaningful contribution. I look forward to learning more about the project and discussing how I can best contribute to the organization.
Thank you for your consideration, and I am looking forward to hearing from you soon.

**Comment by Rainzler-Exagone** [comment]
Hi ,

my name is YASSER and i 'm a CS ungraduated .and i am very excited to be part of this programme ,
i have a good background in web dev (CSS,HTML) and also in android ,ios development (Flutter) databases (Sqlite,HIVE,MySql,Firebase) ,as I see the opportunity that GSoC offers to students and others to enhance and developpe their thinking and experience the real problems and solve them . I used this opportunity to explore and contribute for the organization.
thank for the consideration ,and i 'm looking for the reply with excitement.

**Comment by jagisong** [comment]
Hello everyone!!
I am Jagdish, currently a 3rd year undergraduate student at IIT Roorkee and i am very excited to work on this project. I have good command on HTML,CSS,JAVASCRIPT,SQL and basic knowledge of JSON SCHEMA and python al well. With all this knowledge i believe GSOC is best opportunity for me to gain more experience and enhance my skills. I am looking forward to contribut in this project. 
Thanks you

**Comment by Gbahdeyboh** [comment]
Hey folks, the Postman OSPO is live for a Google Summer of Code Q&A session. #gsoc
Link to zoom session: [go.pstmn.io/gsoc-qa](http://go.pstmn.io/gsoc-qa)

**Comment by Scave-Shark** [comment]
@benjagm  is there any work is going on this project
