### ISSUE TITLE
JSON Fingerprinting

### ISSUE THREAD

**Issue by kulnor** [postman-open-technologies/gsoc-2023#2]
**Scope:**
This project aims to develop tools for comparing JSON and YAML files to determine if they are the same or closely related. This is in our case particularly important for comparing API definitions that may be published in different formats or change over time across versions.  The focus will be on creating algorithms to generate fingerprints and other signatures for these files, which can then be used to compare them for exact or near matches, or to identify differences. The ultimate goal is to create APIs that make these tools available as a service.

**Skills**: Python, JavaScript, and/or Rust;  JSON / YAML; API implementation; Postman; 

**Mentors**: Pascal Heus, ???.

**Size of Project**: 175 or 350 hours

**Comment by jansche** [comment]
This one is exciting. But as this would be a new project, we will probably face challenges with getting it approved:
> Projects can range from being relatively new (about 2 years old) to well established projects that started over 20 years ago. We welcome open source projects big, small, and everything in between. One thing to remember is that open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.

**Comment by kulnor** [comment]
Based on Google SoC "existing project with solid community" criteria, this won't quality. Suggest keeping for internships or other opportunities supporting innovation.
