### ISSUE TITLE
AsyncAPI: Simulator Desktop Application

### ISSUE THREAD

**Issue by NektariosFifes** [postman-open-technologies/gsoc-2023#22]
In gsoc 2021 me and Jonas Lagoni created the asyncApi simulator which uses the Async Api specification and a related schema defined file to generate aynchronous traffic using asynchronous protocols.

https://github.com/asyncapi/simulator

For gsoc 2023 i aspire to turn the cli application into a full desktop application with multiple features. Along with the creation of the application i will add support for the kafka protocol and create rich documentation for the project.
I will specify further details regarding the desktop application in the following days.

Any thoughts?

### Project requirements

- [ ] User stories
- [ ] Developer stories
- [ ] Non functional requirements
- [ ] Functional requirements
- [ ] Implementation details

#### Common Vocabulary
|word | meaning |
|--- | --- |
|simulation| A simulation is a collection of scenarios that are executed on existing services based on the AsyncAPI. It can be stress testing an application, simulating specific environments, etc.|

#### Functional requirements
|id | Description |
| --- | ---- |
|#F1 | User should be able to use the toolbar to add a asyncapi file that describes the targeted api
|#F2 | User should be able to use the toolbar to add a scenario file that describes a sequence of asynchronous traffic that should be generated
|#F3 | User should be able to use the toolbar to add a scenario file that describes a sequence of asynchronous traffic that should be generated
|#F4 | User should be able to use an in app editor to edit his scenario file
|#F5 | User should be able to see an organized representation of his AsyncApi file similar to that of asyncApi playground
|#F5 | The above organized representation will have a generate button for each endpoint which will be used by the user to generate a request
#### Non-functional requirements
|id |  Description |
| ---  | ---- |
|#NF1 | The application will  work with vanilla react and electron

#### User stories
|id | Prioritization | Description |
| --- | -- | ---- |
|#S1 | | 

#### Developer stories
|id | Prioritization | Description |
| --- | ----| ---|
|#DS1 |  | 

#### Implementation details
|id | Prioritization | Description |
| --- | ----| ---|
|#S1 |  |

**Comment by ishaan812** [comment]
Hey, would love to help. I have quite a bit of experience working with Kafka and can help with some other stuff as well. If you could detail what aspect of the project you need help with.

**Comment by NektariosFifes** [comment]
@ishaan812 Hello :), we could start by listing what the desktop application is supposed to do. You could check out the 'game processor' example in simulator repo if you are interested in learning more. I will also add a blueprint of what the application layout will be like and edit it according to the requirements.

**Comment by jansche** [comment]
@AceTheCreator This is a GSoC project suggestion. If you consider it a potential idea for GSoC, please reach out to @NektariosFifes. Otherwise instructions on how to suggest it to [AsyncAPI](https://github.com/asyncapi) outside of GSoC are appreciated.

**Comment by ishaan812** [comment]
Alright @NektariosFifes will try that out to get a better sense of the project. Definitely share some more details whenever you can.

**Comment by NektariosFifes** [comment]
@jansche @AceTheCreator So if this is not considered a potential idea there is no chance of it being chosen? Can i get some feedback :)?

**Comment by NektariosFifes** [comment]
@ishaan812 ok if you have questions or some suggestion you can also open an issue on the simulator repo :)

**Comment by ishaan812** [comment]
Yes will do!

**Comment by AceTheCreator** [comment]
@NektariosFifes I think this project should be proposed as part of the upcoming AsyncAPI mentorship program. Despite receiving more than five project ideas for GSoC, we decided to propose five project ideas.

**Comment by lbroudoux** [comment]
Hi there!

Ever considered joining forces with the [Microcks](https://microcks.io) (https://github.com/microcks/microcks) project? We support mocking/simulation through AsyncAPI support and already have a number of protocols (Kafka, MQTT, WebSocket, Rabbit, NATS and Google PubSub). There's still some place for improvements, and additional protocols but also new ways of consuming/using Microcks (we started recently working on a Docker Desktop Extension to have a frontend on the developer's laptop).

Feel free to reach if interested in!

**Comment by Gbahdeyboh** [comment]
Hey folks, the Postman OSPO is live for a Google Summer of Code Q&A session. #gsoc
Link to zoom session: [go.pstmn.io/gsoc-qa](http://go.pstmn.io/gsoc-qa)
