### ISSUE TITLE
Idea for GSOC 2023

### ISSUE THREAD

**Issue by princerajpoot20** [postman-open-technologies/gsoc-2023#23]
Hello,
I’m Prince Rajpoot, 2nd year B-tech student.
I want to contribute to Postman as a part of GSOC 2023.

Postman is a popular tool for API development and testing, and contributing to the project can help you learn more about this area.

I want to suggest an idea:

Data Generator - Random data generator like email, names, zip/postal codes, addresses, mobile number and provide the facility to verify response in random data generator.

What are your views on this? Can I contribute to this idea as a part of GSOC-2023?
I'm really passionate about this project and I believe it has the potential to make a real impact. I would be so grateful for any help you could provide.

-Prince Rajpoot
[prince.rajpoot.20@gmail.com](mailto:prince.rajpoot.20@gmail.com)

**Comment by vinitshahdeo** [comment]
Hey @princerajpoot20 

Thanks for showing your interest. A [similar feature](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/) already exists in Postman.  Is your idea different from what we already have? 

PS: We internally use the [faker](https://www.npmjs.com/package/@faker-js/faker) npm library to power the same.

**Comment by shukla2004** [comment]
hey ,
i am kirti shukla 
i have go through the site postman.com and i  find it little confusing using it as a new user but i can make it look simpler and more understandable for a new user 
i wanna know your thought on this idea 
i want to contribute to this project also for the purpose of GSOC 2023

**Comment by jansche** [comment]
@princerajpoot20 I'll close the issue as the idea would not qualify for GSoC (not contributing to an exisiting Open Source project). If you feel like this is not appropriate or your intention was different from what we understood, please reach out to us.
