### ISSUE TITLE
Want to integrate POSTMAN to vs code as extension. 

### ISSUE THREAD

**Issue by suhailopensource** [postman-open-technologies/gsoc-2023#24]
Since postman needs to be installed as a separate software many of my friends who were hardcore postman users shifted to thunderclient as it open in vs code. not only my fruiends but many people. so if postman launches their extension it will gain all its lost users bcoz their UI was superb.

**Comment by MikeRalphson** [comment]
This is already planned. See this [tweet](https://twitter.com/getpostman/status/1634255718432776193)

**Comment by jansche** [comment]
Thanks for the suggestion, @suhailopensource . As @MikeRalphson mentioned, that feature is already planned. We appreciate your engagement in the Open Source community and would love to see you on one of the other suggested project ideas for GSoC 2023. Or feel free to suggest a new project idea. We're curious to hear from you.

Closing this issue as a duplicate.
