### ISSUE TITLE
GraphQL Metadata Extensions

### ISSUE THREAD

**Issue by kulnor** [postman-open-technologies/gsoc-2023#3]
**Scope:** 
No data should be delivered without documentation, which should not only be accessible to users, but also available in machine actionable to enable application driven processing and analysis, APIs, machine learning, or artificial intelligence. 

This project aims to explore the integration of metadata standards, such as W3C DCAT (https://www.w3.org/TR/vocab-dcat-2), the Data Documentation Initiative (https://ddialliance.org/), or schema.org (https://schema.org/docs/data-and-datasets.html), with GraphQL APIs to enhance the discoverability, accessibility, and reusability of data. The project will focus on demonstrating how GraphQL schema extensions can be used to inject standard-based metadata into GraphQL-based APIs, thus strengthening the power of the specification and enabling more efficient data processing and analysis through APIs, machine learning, and artificial intelligence. The goal is to align with the FAIR initiative (https://www.go-fair.org/), which promotes data that is Findable, Accessible, Interoperable, and Reusable

**Skills**: JavaScript, and/or Rust;  GraphQL; GraphQL Yoga; JSON/XML; Research Data Management; Metadata standards;

**Mentors**: Pascal Heus, Doc Jones

**Size of Project**: 350 hours

**Comment by jansche** [comment]
Is this depending on the other metadata project? If so, how can we secure this project can be worked on independently? Would also need a more detailed description.

**Comment by kulnor** [comment]
Based on Google SoC "existing project with solid community" criteria, this won't quality. Suggest keeping for internships or other opportunities supporting innovation.
