### ISSUE TITLE
GraphQL for Metadata Standards

### ISSUE THREAD

**Issue by kulnor** [postman-open-technologies/gsoc-2023#4]
**Scope:**
No data should be delivered without documentation, which should not only be accessible to users, but also available in machine actionable to enable application driven processing and analysis, APIs, machine learning, or artificial intelligence

This project aims to improve the accessibility and usability of data documentation by developing a GraphQL-based API for the W3C DCAT (https://www.w3.org/TR/vocab-dcat-2) and the Data Documentation Initiative (https://ddialliance.org) metadata standards. These provide a way to describe and organize data, but lack a generic API that enables easy access and integration with other tools. Our initial research (https://medium.com/@plgah/graphql-for-metadata-standards-b6df8fb12f3a) suggests that GraphQL can be used to rapidly create and even auto-generate schemas and APIs for such specifications. We are seeking to further explore this idea which would not only be game changing but lay the ground for a similar approach for other standards.

**Skills**: GraphQL; GraphQL Yoga; JSON / XML; Postman; Research Data Management; Metadata standards;

**Mentors**: Pascal Heus, Doc Jones

**Size of Project**: 175 or 350 hours

**Comment by jansche** [comment]
Could this be considered part of the GraphQL OS project? Asking because

> open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.

**Comment by doc-jones** [comment]
> Could this be considered part of the GraphQL OS project? Asking because
> 
> > open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.

This project fits better in a data community than in GraphQL. I'm sure Pascal can choose an appropriate one.

**Comment by kulnor** [comment]
Based on Google SoC "existing project with solid community" criteria, this won't quality. Suggest keeping for internships or other opportunities supporting innovation.
