### ISSUE TITLE
Metasheet

### ISSUE THREAD

**Issue by kulnor** [postman-open-technologies/gsoc-2023#5]
**Scope:**
No data should be delivered without documentation, which should not only be accessible to users, but also available in machine actionable to enable application driven processing and analysis, APIs, machine learning, or artificial intelligence

This project aims to improve and enhance the open-source Python package Metasheet (https://pypi.org/project/metasheet/), which was developed to facilitate the rapid documentation of datasets using a simple spreadsheet-based template. While this approach is not uncommon, metasheet differentiates itself by being aligned with global standards such as the Data Documentation Initiative (https://ddialliance.org/) and the Generic Statistical Information Model (GSIM), which support the FAIR initiative (https://www.go-fair.org) for making data Findable, Accessible, Interoperable, and Reusable. 

The package was initially developed as an internal tool and while functional, it has limited documentation and could benefit from upgrades and enhancements. This project would focus on transforming Metasheet into a robust open-source package, ready for prime time and contribution from other developers, by adding additional functionalities or serializers, improve documentation, and address any underlying code issues.

**Skills**: Working knowledge of Python; Familiarity with research data management and/or metadata standards and  best practices such as FAIR, DDI, GSIM, DCAT is a plus.

**Mentors**: Pascal Heus (), ???

**Size of Project**: 175 or 350 hours

**Comment by jansche** [comment]
Can we handle this requirement, @kulnor?
> open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.

**Comment by kulnor** [comment]
Based on Google SoC "existing project with solid community" criteria, this won't quality. Suggest keeping for internships or other opportunities supporting innovation. In this case there are too few contributors.
