### ISSUE TITLE
Schema.org OpenAPI Catalog

### ISSUE THREAD

**Issue by jansche** [postman-open-technologies/gsoc-2023#6]
**Summary:** Create an open catalog of OpenAPI definitions for each of the [Schema.org](https://schema.org/) Types. Providing a robust set of starting OpenAPI templates for teaching or developing new APIs using a design-first approach. Helping save developers work when it comes to starting new APIs, but also help ensure APIs are developed using common standards and are as interoperable as possible.

**Skills:** Familiarity with the OpenAPI specification, and Schema.org Types.

**Expected Outcomes:** A public repository of up-to-date OpenAPI 3.1 definitions and validated JSON Schema instances for each of the Schema.org Types. You must share your code used to generate the output definitions, allowing them to be updated as schema.org Types evolve.

**Mentors:** @MikeRalphson + 1-2 additional mentors to be named.

**Project Repo:** https://github.com/postman-open-technologies/schema-org-openapi-catalog

**Size of Project:** 175h or 350h

**Rating:** Medium skills level

**Comment by jansche** [comment]
Will need to fit within requirement of being a "175 and 350-hour projects".

**Comment by Pavan-Nambi** [comment]
Hello @jansche ,

I hope this message finds you well. I was wondering if you could clarify the qualification task that needs to be completed for this, as described in the [CONTRIBUTOR_GUIDANCE](https://github.com/postman-open-technologies/gsoc-2023/blob/main/CONTRIBUTOR_GUIDANCE.md), should i make a repo and try to make open api definitions for some schema.ord objects?

and there seems to be a typo here , in remaining issues its mentioned as 18/18+ mentors and here 16

Thank you for your time and assistance.

**Comment by money8203** [comment]
Hey @jansche, I am currently a Postman Student leader and a junior web developer.

 I have had some experience with API's and Postman before. Would love to work on the Open API initiative along with the amazing team at Postman!

**Comment by money8203** [comment]
Hey Myself Manish. I am currently a Postman Student Leader and a junior developer pursuing my bachelor's in Computer Science and Engineering.

As a developer, I am interested in this project because it can save a lot of time and effort when starting new APIs. By having an open catalog of OpenAPI definitions for each of the Schema.org objects, we can have a robust set of starting templates for designing new APIs, and ensure that they are developed using common standards and are interoperable.

As a mentee, I would appreciate clear instructions and regular feedback from my mentors. I would also appreciate their availability for questions and support as I work on the project.

As I work on this project, I plan to familiarize myself with the OpenAPI specification and Schema.org objects, and keep up-to-date with changes in these areas. I may also explore code used to generate OpenAPI definitions and see if there are ways to optimize it. Along with my studies 

As a developer, I like to keep myself organized using project management software. I also use version control systems, such as Git, to keep track of changes and collaborate effectively with my team members. I prefer to use collaborative platforms, such as Slack or Microsoft Teams, for communication and sharing resources.

**Comment by jansche** [comment]
Hi,
Thank you for your interest!  We'll be providing more details over the course of next week. Please stay tuned.
Cheers

**Comment by yashm277** [comment]
Hey! 
I’m Yash Mundada a second year CS student at BITS Pilani and was interested in contributing to Postman for GSOC '23.
This is not the first time that I have been involved with Postman. I help run the Postman funded lab at BITS Pilani, have also completed the Postman student qualification and had discussions with Abhijit Kane (a cofounder of Postman who is from BITS) about entrepreneurship when he had visited our campus. I have found these experiences to be invaluable and was hoping to have another positive experience by contributing to GSOC.

**Comment by MikeRalphson** [comment]
Hi @money8203 @Pavan-Nambi @yashm277 thank you for your interest in this project.

We have now created a repository here: https://github.com/postman-open-technologies/schema-org-openapi-catalog

Please look at the issues labelled "Good first issue" and consider taking on one or more of them as your qualifying task. You can comment on the issue with your findings and approaches, as well as asking questions.

I look forward to your applications!

**Comment by Himanshu-Dedha** [comment]
Hello Guys!!
I'm Himanshu, a third year Electronics and Computer Science student at YMCA Faridabad. I'd love to contribute to Postman, but the issue list you provided to look into leads to 404 not found. Could you guys please look into it? @MikeRalphson

**Comment by MikeRalphson** [comment]
@Himanshu-Dedha thanks! Link made absolute now.

**Comment by Gbahdeyboh** [comment]
Hey folks, the Postman OSPO is live for a Google Summer of Code Q&A session. #gsoc
Link to zoom session: [go.pstmn.io/gsoc-qa](http://go.pstmn.io/gsoc-qa)

**Comment by money8203** [comment]
Hey @MikeRalphson can I propose the proposal for combining the #6 and #8 project and working together ? Or do I need to submit individual proposal for each of them!!

**Comment by MikeRalphson** [comment]
> Hey @MikeRalphson can I propose the proposal for combining the #6 and #8 project and working together ? Or do I need to submit individual proposal for each of them!!

Hi @money8203 you can submit a proposal for the combined projects, but to maximise your chance of being selected, please complete a full section of your proposal for each project, so we could break it up if we need to. Thank you.

**Comment by money8203** [comment]
Sure, thanks for the feedback!

**Comment by pragya-20** [comment]
Hello there!
I am Pragya Bhardwaj, a software developer based in India. I am excited to express my interest in working on this project as I personally experienced the challenges of understanding APIs when I started working. It took me a while to understand the concepts and I had to connect with my peers to grasp the practical application of APIs.

While researching the Open API specification, I was immediately drawn to its potential to make API development more accessible and efficient. Contributing to this project would enable me to make a meaningful impact by simplifying the process for developers to start on any new API and save their valuable time.
I have reviewed the Open API and Schema.org documentation and watched related videos to gain a better understanding of the feature. My expertise lies in working with JavaScript, JSON, React, and React Native, and I possess significant experience developing software applications using these technologies.
I follow standard coding practices such as Prettier and ESLint for formatting and linting, and my go-to tools include VS Code, Bitbucket, Git, and Github. My skill set aligns with the requirements of GSOC 2023, and I am excited to contribute to this project.

@MikeRalphson, I started analyzing the good first issues and will submit the proposal for the same soon. 

Thanks :)

**Comment by pragya-20** [comment]
Hi @MikeRalphson, is there any other good first issue present to work or should I work on the ones which you have previously mentioned?

> We have now created a repository here: https://github.com/postman-open-technologies/schema-org-openapi-catalog

> Please look at the issues labelled "Good first issue" and consider taking on one or more of them as your qualifying task. You can comment on the issue with your findings and approaches, as well as asking questions.

**Comment by MikeRalphson** [comment]
These are the only qualifying tasks.

**Comment by pragya-20** [comment]
Okay, got it. I will also add my inputs there.
Thanks @MikeRalphson !

**Comment by pragya-20** [comment]
Hi @MikeRalphson / @saialekhya-001 / @sourabhbagrecha, I want to understand a few things here:
1. Are we going to write OpenAPI definitions for the schema.org based APIs on different types or do we need to define OpenAPIs for the schema.org types itself?
Why I am asking this because OpenAPI definitions can be written for APIs and schema.org types are not APIs then how can we achieve this?

**Comment by MikeRalphson** [comment]
> Hi @MikeRalphson / @saialekhya-001 / @sourabhbagrecha, I want to understand a few things here:
> 1. Are we going to write OpenAPI definitions for the schema.org based APIs on different types or do we need to define OpenAPIs for the schema.org types itself?
> Why I am asking this because OpenAPI definitions can be written for APIs and schema.org types are not APIs then how can we achieve this?

"do we need to define OpenAPIs for the schema.org types itself?"

Yes, this is the project goal.

**Comment by pragya-20** [comment]
Alright! but I am reading this documentation which says this:

> The OpenAPI Specification allows the description of a remote API accessible through HTTP or HTTP-like protocols.

Reference: https://oai.github.io/Documentation/introduction.html
And the schema.org types are not APIs, right? Sorry, I am not understanding it completely. I understand Schema.org and OpenAPI separately, but I am quite unsure about if we can write OpenAPI definitions for Schema.org types.
Can you please shed some light here?

**Comment by pragya-20** [comment]
@MikeRalphson, I dug dip and understood that though the schema.org types are not APIs we can still write the OpenAPI definitions to describe the structure of data that we want to exchange using those types. This can also help if one wants to create an API that uses Schema.org types to represent data.

**Comment by benjagm** [comment]
Closed as completed as part of 2023 edition.
