### ISSUE TITLE
OpenAPI Componentizer

### ISSUE THREAD

**Issue by jansche** [postman-open-technologies/gsoc-2023#9]
**Summary:** Take any one or more OpenAPI 3.x definitions and loop through and move common objects to be centralized components. In the case of multiple input definitions, the common objects should be extracted to the `components` section of an external OpenAPI definition. Using the `components` object to centralize and reuse `schemas`, `parameters`, `examples`, and other elements of an API. Allowing for more efficient and reusable OpenAPI definitions that maximize the components object of the specification.

**Skills:** Familiarity with the OpenAPI specification.

**Mentors:** @bavulapati @arvindkalra08 @RaisinTen

**Project Repo:** https://github.com/postman-open-technologies/openapi-componentizer

**Project Size:** 175h

**Rating:** Medium

**Comment by jansche** [comment]
Needs more details.  Seems rather small in terms of scope. Could this even be a 175h project. Could it be a child project to the OpenAPI Initiative? @kinlane

**Comment by money8203** [comment]
Hey @jansche , I am currently a Postman Student leader and a junior web developer.

I have had some experience with API's and Postman before. Would love to work on the Open API initiative along with the amazing team at Postman!

This project's most interesting aspect is the opportunity to create a solution that simplifies the search interface and handles conducting a search asynchronously. The challenge of developing an open-source API that allows users to search for OpenAPI definitions on Github while managing the platform's rate limits could also be an exciting part of this project for me.

You can get the best out of me by providing clear and concise instructions and objectives for each task, I can work tirelessly on tasks and can quickly learn new skills that are necessary for the project's success.

**Comment by Devaansh-Kumar** [comment]
Could more specific information be given about what the task is and how the project will move forward?
Som resources would also be helpful?  @jansche

**Comment by suyash-srivastava-dev** [comment]
Hi @jansche 

I have worked with OpenAPI , swaggers and have understanding as how difficult it get when all the specification are present on a single page. I would like to work on this as have faced this problem of recurring schema definitions.

**Comment by Polaris66** [comment]
Hi,
I am Dhruv Arora, a second year Computer Science Student. 

I have been learning and using Postman for some time now and I woud love to contribute in any way that I can.

AsyncAPI Document Optimizer project from GSOC 2021, introduces a lot of features similar to the one required.
I also think that this project could be somewhat smaller than required, however you can always add more features to optimize/refactor OpenAI definitions better. In fact, I think the project should be changed to making an OpenAI definition Optimizer including all required functionality.

**Comment by jansche** [comment]
Hi folks,
we're currently coordinating mentors and will provide more details as well as answer questions beginning of next week (week of February 27). Please bear with us.
Best regards
Jan

**Comment by shaunak-09** [comment]
Hey @jansche  can you pls give some more information about the project and how to proceed with this

**Comment by Devaansh-Kumar** [comment]
Hi everyone I am Devaansh Kumar a 2nd year CSE student at NIT Surathkal. I have familiarized myself with OpenAPI specs and its interesting to see the rise and need of well defined specifications for APIs. Could more information be given about what particular definitions will the project be about?

**Comment by Devaansh-Kumar** [comment]
Hey @jansche, where is the task available for this project?

**Comment by bavulapati** [comment]
Hi folks!

Happy to see the expression of interest :rocket: . We are currently defining the scope of the project. Once we finalise that, we will come up with the project repository and the tasks for you to pick up and show your enthusiasm.

Thanks for understanding!
Bala

**Comment by jansche** [comment]
I updated the issue description with the link to the project repo: https://github.com/postman-open-technologies/openapi-componentizer
There will be more details on how to engage and qualify very soon! Stay tuned!

**Comment by orubel** [comment]
why is @kinlane attached to this at all? He doesn't seem to even be part of the project or have anything to do with this?

**Comment by AishwaryJain07** [comment]
hi @jansche 
I'm Aishwary Jain , a second year CSE undergraduate
i have knowledge of and worked with openai and understand it's workings. I would like to contribute in 2024 projects under your mentorship in GSOC'24.

**Comment by benjagm** [comment]
Closed as completed as part of 2023 edition.
